from __future__ import annotations

import os
from typing import Protocol, runtime_checkable


@runtime_checkable
class AsyncFileIO(Protocol):
    async def read(self, size: int = -1) -> bytes: ...
    async def write(self, data: bytes) -> int: ...
    async def seek(self, offset: int, whence: int = os.SEEK_SET) -> int: ...
    async def aclose(self) -> None: ...
